### ISSUE TITLE
Cannot programmatically close the media session (ios & web)

### ISSUE THREAD

**Issue by sanderschnydrig** [jofr/capacitor-media-session#7]
Hi there

I'm having issues closing the session on iOS and web. It only closes after closing the app. Works just fine on Android.

```typescript
this._audioContext.pause()
MediaSession.setPlaybackState({ playbackState: 'none' })
```

```bash
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.6.1
  @capacitor/core: 4.6.1
  @capacitor/android: 4.6.1
  @capacitor/ios: 4.6.1

Installed Dependencies:

  @capacitor/cli: 4.6.1
  @capacitor/core: 4.6.1
  @capacitor/android: 4.6.1
  @capacitor/ios: 4.6.1

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

```bash
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 13.3.10
Node: 16.19.0
Package Manager: npm 8.19.3
OS: darwin arm64

Angular: 13.3.12
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1500.4
@angular-devkit/build-angular   13.3.10
@angular-devkit/core            15.0.4
@angular-devkit/schematics      13.3.10
@angular/cdk                    13.3.9
@angular/cli                    13.3.10
@angular/fire                   7.5.0
@angular/flex-layout            13.0.0-beta.38
@angular/material               13.3.9
@schematics/angular             13.3.10
rxjs                            6.6.7
typescript                      4.6.4
```

**Comment by jofr** [comment]
Hi, so I think the problem is the following:

The browser implementation of the Media Session Web API (which is used on web/iOS) uses something called the _actual playback state_ to determine if it shows the notification. This _actual playback state_ is 'playing' if manually set to 'playing' (using `setPlaybackState`) and otherwise has the value of the _guessed playback state_. This _guessed playback state_ is something the browser determines to be either 'playing' or 'paused' as long as there are media elements in the document that are either playing or paused. So even if you are manually setting the playbackState to 'none' the _actual playback state_ will still be 'paused' (because you just paused the audio in your example and therefore the browser still detects an active and paused media element in the document). This is explained in [more detail here in the W3C standard](https://w3c.github.io/mediasession/#playback-state-model) but I think this is the reason why the notification is still showing.

On Android it is a bit different. The plugin has no way to know whether there are any playing or paused media elements inside the document, so the plugin just trusts that the information provided via `setPlaybackState` is correct and interprets the 'none' value as 'no active playing or paused media' and stops the media session and notification from showing.

So to solve this you have to make sure that the playback state _guessed_ by the browser is not 'paused' or 'playing' when setting the playbackState to 'none'. There might be implementation differences between browsers here but at least on mobile Chrome this can e.g. be done by setting `audioElement.src = ''`. I hope this helps!
